
/**************************************************************
 *	
 *	specialbgm2, 8 bit, 11025Hz,
 *	1 channel, 44100 bytes/channel
 *	Total Size: 1 * 44100 + 4 (header) = 44144 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\So-mi\Desktop\soundlabassets\specialbgm2.wav
 *	Time-stamp: Wed Oct 12 16:35:44 2011
 *	
 **************************************************************/

#ifndef __SPECIALBGM2H__
#define __SPECIALBGM2H__

#define SPECIALBGM2FREQ 11025
#define SPECIALBGM2LEN 44100

extern const unsigned char specialbgm2[44100];

#endif /* __SPECIALBGM2H__ */
